# Netflix Data Analysis Using Python

## Auspify Technologies Internship Project

**Project:** Netflix Data Analysis  
**Tools Used:** Python, Pandas, Matplotlib, Jupyter Notebook

### Project Objective
The objective of this project is to clean, analyze, and visualize the Netflix dataset to identify content distribution, country-wise patterns, and release year trends.

# TASK 1 - NETFLIX DATA CLEANING & PREPARATION

In [1]:
import pandas as pd

print("Pandas imported successfully!")

Pandas imported successfully!

In [2]:
df = pd.read_csv("Dataset.csv")

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [3]:
df.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

In [4]:
df.shape

(8790, 10)

In [5]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   str
 1   type          8790 non-null   str
 2   title         8790 non-null   str
 3   director      8790 non-null   str
 4   country       8790 non-null   str
 5   date_added    8790 non-null   str
 6   release_year  8790 non-null   int64
 7   rating        8790 non-null   str
 8   duration      8790 non-null   str
 9   listed_in     8790 non-null   str
dtypes: int64(1), str(9)
memory usage: 686.8 KB

In [7]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
print("Missing Values:")
print(df.isnull().sum())

print("\nDuplicate Records:")
print(df.duplicated().sum())

Missing Values:
show_id         0
type            0
title           0
director        0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
dtype: int64

Duplicate Records:
0

In [10]:
df[['type', 'country', 'rating']].head(10)

      type         country rating
0    Movie   United States  PG-13
1  TV Show          France  TV-MA
2  TV Show   United States  TV-MA
3    Movie          Brazil  TV-PG
4    Movie   United States  TV-MA
5  TV Show  United Kingdom  TV-14
6    Movie   United States  PG-13
7    Movie           India  TV-Y7
8    Movie         Germany  TV-MA
9    Movie           India  TV-Y7

In [11]:
df['type'] = df['type'].str.strip()
df['country'] = df['country'].str.strip()
df['rating'] = df['rating'].str.strip()

print("Columns standardized successfully!")

Columns standardized successfully!

In [12]:
df.to_csv("Netflix_Cleaned_Dataset.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!